### ISSUE TITLE
Brief writeup on mentor requirements

### ISSUE THREAD

**Issue by rosskukulinski** [knode/mentor#4]
What does it take to be a mentor?
- Time commitment
- Experience
- How many mentees (we're pitching max 5 to begin with, staggered in adding)

(@rosskukulinski ask @hackygolucky for the picture taken from KnodeCamp whiteboard)

**Comment by hackygolucky** [comment]
Aw shoot. I started transcribing this as a Google Doc. I should switch it
over to a repo.

**Comment by rosskukulinski** [comment]
@hackygolucky I posted the picture you sent me in #5.  Not sure if you have additional material beyond that.

**Comment by hackygolucky** [comment]
I have other pictures but the quality is low. I'd rather just post what I
transcribed.
